motor_inertia: 0.000191658
static_friction_gain: 0.1
viscous_friction_gain: 0.1
global_friction_gain: 0.4
acceleration_differentiator_order: 5
acceleration_filter_order: 5
acceleration_filter_cutoff: 30.0
torque_sensor_filter_order: 4
torque_sensor_filter_cutoff: 30.0
inertia_compensation_gain: 0.8
command_filter_order: 4
command_filter_cutoff: 30.0
ripple_phase_offset: 0.0
ripple_amplitude: 0.0
ripple_compensation_gain: 0.0
use_filtered_torque_sensor: true
use_filtered_acceleration: true
use_filtered_command: true
torque_differentiator_order: 5
torque_derivative_filter_order: 5
torque_derivative_filter_cutoff: 30.0
torque_derivative_feedback_gain: 0.0

