motor_inertia: 0.000191658
static_friction_gain: 0.1
viscous_friction_gain: 0.1
global_friction_gain: 0.9
acceleration_differentiator_order: 5
acceleration_filter_order: 5
acceleration_filter_cutoff: 500.0
torque_sensor_filter_order: 4
torque_sensor_filter_cutoff: 500.0
inertia_compensation_gain: 0.9
command_filter_order: 4
command_filter_cutoff: 500.0
ripple_phase_offset: 0.0
ripple_amplitude: 0.0
ripple_compensation_gain: 0.0
use_filtered_torque_sensor: false
use_filtered_acceleration: false                                            
use_filtered_command: false
torque_differentiator_order: 5
torque_derivative_filter_order: 5
torque_derivative_filter_cutoff: 30.0
torque_derivative_feedback_gain: 0.0
